### ISSUE TITLE
Failed while running the "preprocess_data.py" of the DeepSDF project

### ISSUE THREAD

**Issue by WanquanF** [B1ueber2y/DIST-Renderer#1]
I failed while running the "preprocess_data.py" of the DeepSDF project. There are 22 issues in that project. It seems that none of the askers solved their problems. have you ever meet the problem that the folder of the output data is empty? It's very strange. I'll appreciate if you can tell me how you get the results successfully!

**Comment by B1ueber2y** [comment]
I am not very sure about your case but I remember that I resolved this issue by disabling the X11 forwarding. A straightforward solution might be to run the script on your tabletop with the GUI. Also, you might need to make sure that the script is correctly compiled and called. To have the error log, you could directly run the generated execution script ./bin/PreprocessMesh with specific input arguments rather than calling via the Python script. 

Thanks!

**Comment by WanquanF** [comment]
Thanks for the reply! I followed your advice and tested on my PC(ubuntu16) with GUI. I didn't use the headless scheme, and runs the ./bin/PreprocessMesh directly. The error is now like this:
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.GLSL Shader compilation failed: <string>:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

OpenGL Error 500: GL_INVALID_ENUM: An unacceptable value is specified for an enumerated argument.

**Comment by B1ueber2y** [comment]
Sorry for that I have not met the same problem. But I just found a related issue in the DeepSDF repo which might help a little bit:

https://github.com/facebookresearch/DeepSDF/issues/14

I believe that the OpenGL Error 500 should be fine because I remember that I could successfully generate the files with this error being reported. So I guess the problem could be on the GLSL version. However, I cannot reproduce this issue so the problem is not very clear to me.

Thanks!

**Comment by WanquanF** [comment]
I have solved this problem by using another PC. Thanks a lot!
