### ISSUE TITLE
How do you reconstruct the internal geometry of the car in multi-view reconstruction?

### ISSUE THREAD

**Issue by callmexg1** [B1ueber2y/DIST-Renderer#6]
Hi! @B1ueber2y Thanks for your wonderful work! I have successfully run your multi-view reconstruction code. But I find that car‘s internal geometry can be well reconstructed, which seems unreasonable under multi-view guidance. Could you please share your dataset for your pre-trained DeepSDF model?

**Comment by B1ueber2y** [comment]
Thanks for the questions. As stated in the paper, we use the same training set as DeepSDF, which is from ShapeNet. Yes the internal geometry can not be reconstructed under multiview guidance from the geometric perspective. So that could be the case when the shape priors are generalized to the test case successfully, thanks to the DeepSDF representation.
